"""Added account_acter table

Revision ID: de9a16241400
Revises: 
Create Date: 2025-01-13 19:43:23.980823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9a16241400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('show', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('part', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name_show', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('mane_show', sa.String(), nullable=False),
    sa.Column('acter', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posters',
    sa.Column('name_poster', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('acter', sa.String(), nullable=False),
    sa.Column('acter_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['acter_id'], ['acters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posters')
    op.drop_table('tickets')
    op.drop_table('shows')
    op.drop_table('products')
    op.drop_table('acters')
    # ### end Alembic commands ###
